name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install shUnit2
        run: |
          git clone https://github.com/kward/shunit2.git
          sudo cp shunit2/shunit2 /usr/local/bin/
          sudo chmod +x /usr/local/bin/shunit2
      - name: Run Tests
        run: ./tests/run_tests.sh
